---
title: "plots and analysis fb2 terriers"
author: "Lucrezia Lonardo"
date: "03/11/2020"
output: html_document
---

```{r setup, include=FALSE}
rm(list=ls())

library(lme4)
library(ggthemes)
library(psych)
library(summarytools)
library(cowplot)
library(car)
library(tidyverse)
library(readr)
library(ggsignif)
source("functions/diagnostic_fcns.r")
source("functions/glmm_stability.r")
source("functions/boot_glmm.r")

```

##loading data

```{r}

terrier_data <-read_csv("./data/fb2_terrier.csv")%>%
  mutate(correct=as.numeric(ifelse(choice=="baited",0,ifelse(choice=="empty",1,""))))%>%
  mutate(fci_group = as.factor(fci_group))%>%
  mutate(breed= as.factor(breed))%>%
  mutate(condition=recode(condition, "FalseBelief"="False Belief", "TrueBelief"="True Belief"))
summary(terrier_data)
str(terrier_data)


table(terrier_data$sex, terrier_data$breed)
#view(dfSummary(fb_data))

```

## Plotting the choices

```{r}
plot.data <- terrier_data %>%
  group_by(condition)%>%
  summarise(mean.correct=mean(correct), sd.correct=sd(correct), sum.correct=sum(correct), median.correct=median(correct), n.correct=length(correct), se.correct=sd(correct)/sqrt(length(correct)))
plot.data

p.choice<-ggplot(
  data=plot.data, aes(x=condition, y=mean.correct)) +
  geom_bar(stat="identity", alpha=0.5)+
  geom_errorbar(aes(ymin=mean.correct-se.correct, ymax=mean.correct+se.correct), width=.2) +
  ylim(0,0.8)+
  #geom_signif(comparisons=list(c("False Belief", #"True Belief")), annotations="*",
 #             y_position = 0.75, tip_length = 0.07, #vjust=0.4) +
  theme_classic()+
  labs(x="Group",y="Proportion of bucket A choices")+
  ggtitle("Terriers")
 p.choice
 
#saving the plot with ggsave
ggsave(
  "./graphs/bucket_A_choices_terriers.png",
  plot = last_plot(),
  device = NULL,
  #path = "C:/Users/lonardol/Desktop/False Belief experiment/FB_2_follow_up/Graphs/Terriers",
  scale = 0.8,
  width = 5,
  height = 6,
  #units = c("in", "cm", "mm"),
  dpi = 320,
  limitsize = TRUE
)
```

analysing the effect of group on condition: generalised linear mixed model

```{r}
model.data <- terrier_data %>% 
  mutate(z.age = as.numeric(scale(age, scale = T, center = T)),
         sex.c = as.numeric(scale(as.numeric(sex), scale=F, center=T)),
         condition.c = as.numeric(scale(as.numeric(condition), scale=F, center=T)),
         first_baited_box.c = as.numeric(scale(as.numeric(first_baited_box), scale=F, center=T)),
         breed2=as.factor(as.numeric(breed)))

model.data<-as.data.frame(model.data)


xx.fe.re=fe.re.tab(fe.model="correct ~ condition + age + sex + first_baited_box",
                   re="(1|breed)", data=model.data)
xx.fe.re$summary


## code to run the model
full.choice.breed <- glmer(correct ~ condition + z.age + sex + first_baited_box+
             (1+ sex.c + condition.c + first_baited_box.c || breed2), 
             data = model.data, family = binomial, 
             control=glmerControl(optimizer="bobyqa",optCtrl=list(maxfun=2e5)))
summary(full.choice.breed)

full.glm <- glm(correct ~ condition + z.age + sex+first_baited_box , 
             data = model.data, family = binomial, 
             )
summary(full.glm)

drop1(full.glm, test="Chisq")

```
